export const ICONS = {
  next: require("../../assets/icons/next.png"),
  notification: require("../../assets/icons/notification-icon.png"),
  home: require("../../assets/icons/home_icon.png"),
  search: require("../../assets/icons/search_icon.png"),
  tickets: require("../../assets/icons/tickets_icon.png"),
  user: require("../../assets/icons/user_icon.png"),
  heart: require("../../assets/icons/heart_icon.png"),
  fullheart: require("../../assets/icons/full_heart_icon.png"),
  location: require("../../assets/icons/location_icon.png"),
  time: require("../../assets/icons/clock-icon.png"),
  edit: require("../../assets/icons/edit-image-icon.png"),
  right: require("../../assets/icons/right.png"),
  left: require("../../assets/icons/left_arrow.png"),
  settings: require("../../assets/icons/settings_icon.png"),
  information: require("../../assets/icons/information_icon.png"),
  favourite: require("../../assets/icons/favourite_icon.png"),
  logOut: require("../../assets/icons/exit_icon.png"),
  close: require("../../assets/icons/close_icon.png"),
  camera: require("../../assets/icons/camera_icon.png"),
  gallery: require("../../assets/icons/image-gallery_icon.png"),
  delete: require("../../assets/icons/delete_icon.png"),
  down: require("../../assets/icons/down_icon.png"),
  photo: require("../../assets/icons/take_photo__icon.png"),
  flip: require("../../assets/icons/flip_icon.png"),
  pin: require("../../assets/icons/pin_icon.png"),
};
